
phi_ana: phi_ana.cpp
	g++  -Wall -L/Users/tujuba/panda/svn/ext-apr13/lib/root -lCore -lCint -lRIO -lNet -lHist -lGraf -lGraf3d -lGpad -lTree -lRint -lPostscript -lMatrix -lPhysics -lMathCore -lThread -lpthread -lm -ldl -L/Users/tujuba/panda/svn/ext-apr13/lib -lPluto -I/Users/tujuba/panda/svn/ext-apr13/include/root -I/Users/tujuba/panda/svn/ext-apr13/include/pluto  phi_ana.cpp -o phi_ana
