gen: fill.cpp
	clang++  -std=c++11 -stdlib=libc++ -Wall -L/Users/tujuba/panda/svn/ext-apr13/lib/root -lCore -lCint -lRIO -lNet -lHist -lGraf -lGraf3d -lGpad -lTree -lRint -lPostscript -lMatrix -lMinuit -lPhysics -lMathCore -lThread -lpthread -lm -ldl -lEG -I/Users/tujuba/panda/svn/ext-apr13/include/root fill.cpp -o fill
