phi_ana: phi_ana.cpp
	g++ phi_ana.cpp -o phi_ana -Wall -L/vol0/panda/svn/ext-apr13/lib -lPluto -L/vol0/panda/svn/ext-apr13/lib/root -lCore -lCint -lEG -lRIO -lNet -lHist -lGraf -lGraf3d -lGpad -lTree -lRint -lPostscript -lMatrix -lPhysics -lMathCore -lThread -pthread -lm -ldl -rdynamic  -I/vol0/panda/svn/ext-apr13/include/root -I/vol0/panda/svn/ext-apr13/include/pluto  
